/**
 * Central enum definitions — single source of truth shared by
 * Sequelize models, validators, and the frontend contract.
 */

const ADMIN_ROLE = Object.freeze({
  ADMIN: 'ADMIN',
});

const DEVOTEE_CATEGORY = Object.freeze({
  DISCIPLE: 'DISCIPLE',
  NON_DISCIPLE: 'NON_DISCIPLE',
});

const NON_ATTENDING_TYPE = Object.freeze({
  NON_ATTENDING_DISCIPLE: 'NON_ATTENDING_DISCIPLE',
  ATTENDING_NOT_STAYING: 'ATTENDING_NOT_STAYING',
});

const SHARED_ACCOMMODATION = Object.freeze({
  DORMITORY: 'DORMITORY',
  NON_AC_SHARING: 'NON_AC_SHARING',
  AC_SHARING: 'AC_SHARING',
});

const FAMILY_ACCOMMODATION = Object.freeze({
  DELUXE_AC: 'DELUXE_AC',
  PREMIUM_AC: 'PREMIUM_AC',
});

const ADDITIONAL_FAMILY_ACCOMMODATION = Object.freeze({
  DELUXE: 'DELUXE',
  PREMIUM: 'PREMIUM',
});

const PREFERRED_SUBJECT = Object.freeze({
  BHAGAVAD_GITA: 'BHAGAVAD_GITA',
  SRIMAD_BHAGAVATAM: 'SRIMAD_BHAGAVATAM',
  CHAITANYA_CHARITAMRITA: 'CHAITANYA_CHARITAMRITA',
  HARINAMA_CHINTAMANI: 'HARINAMA_CHINTAMANI',
  HOW_TO_STUDY_SB: 'HOW_TO_STUDY_SB',
  HOW_TO_STUDY_CC: 'HOW_TO_STUDY_CC',
  NECTAR_OF_INSTRUCTION: 'NECTAR_OF_INSTRUCTION',
  VAISHNAVA_ETIQUETTE: 'VAISHNAVA_ETIQUETTE',
  QA_SESSION: 'QA_SESSION',
  VAISHNAVA_SONGS: 'VAISHNAVA_SONGS',
  APARADHA: 'APARADHA',
  DEALING_WITH_VAISHNAVAS: 'DEALING_WITH_VAISHNAVAS',
  OTHER: 'OTHER',
});

const SERVICE = Object.freeze({
  SERVICE_COORDINATE_VOLUNTEERS: 'SERVICE_COORDINATE_VOLUNTEERS',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  KITCHEN_DEPARTMENT: 'KITCHEN_DEPARTMENT',
  VEGETABLE_GROCERY_PURCHASE: 'VEGETABLE_GROCERY_PURCHASE',
  STORAGE_INCHARGE: 'STORAGE_INCHARGE',
  PRASADAM_SERVING: 'PRASADAM_SERVING',
  TEMPLE_HALL_CLEANING: 'TEMPLE_HALL_CLEANING',
  KITCHEN_CLEANING: 'KITCHEN_CLEANING',
  PRASADAM_HALL_CLEANING: 'PRASADAM_HALL_CLEANING',
  WATER_ARRANGEMENT: 'WATER_ARRANGEMENT',
  DEITY_DEPARTMENT: 'DEITY_DEPARTMENT',
  DEVOTEE_STAYING_ARRANGEMENT: 'DEVOTEE_STAYING_ARRANGEMENT',
  DEVOTEE_CARE_HELP_DESK: 'DEVOTEE_CARE_HELP_DESK',
  KIRTAN: 'KIRTAN',
  KATHA_ARRANGEMENT: 'KATHA_ARRANGEMENT',
  RECORDING: 'RECORDING',
  BOOK_STALL: 'BOOK_STALL',
  CHILDREN_CARE: 'CHILDREN_CARE',
  EMERGENCY_MEDICINE: 'EMERGENCY_MEDICINE',
  FLOWER_GARLAND: 'FLOWER_GARLAND',
  ACCOUNTING: 'ACCOUNTING',
  GROUP_CHANTING: 'GROUP_CHANTING',
  SUPERVISOR: 'SUPERVISOR',
  TIME_KEEPING: 'TIME_KEEPING',
  MIC_MANAGEMENT: 'MIC_MANAGEMENT',
  QUEUE_MANAGEMENT: 'QUEUE_MANAGEMENT',
  SEATING_ARRANGEMENT: 'SEATING_ARRANGEMENT',
  CHAPPAL_ARRANGEMENT: 'CHAPPAL_ARRANGEMENT',
  CLEANING_COMMON_AREAS: 'CLEANING_COMMON_AREAS',
  BATHROOM_CLEANING: 'BATHROOM_CLEANING',
  PERSONAL_SERVANT_SEVA: 'PERSONAL_SERVANT_SEVA',
  COVERING_PRASADAM_VESSELS: 'COVERING_PRASADAM_VESSELS',
  CAR_PARKING: 'CAR_PARKING',
  JOURNEY_PRASAD_PACKING: 'JOURNEY_PRASAD_PACKING',
  CLOTHES_DRYING_ARRANGEMENT: 'CLOTHES_DRYING_ARRANGEMENT',
});

const ACCOMMODATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  NOT_REQUIRED: 'NOT_REQUIRED',
});

const ASSIGNMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
});

const SMS_CAMPAIGN_TYPE = Object.freeze({
  ACCOMMODATION: 'ACCOMMODATION',
  REMINDER_7_DAY: 'REMINDER_7_DAY',
  REMINDER_2_DAY: 'REMINDER_2_DAY',
  CUSTOM: 'CUSTOM',
});

const SMS_CAMPAIGN_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
});

const SMS_LOG_STATUS = Object.freeze({
  SENT: 'SENT',
  FAILED: 'FAILED',
});

const values = (obj) => Object.values(obj);

module.exports = {
  ADMIN_ROLE,
  DEVOTEE_CATEGORY,
  NON_ATTENDING_TYPE,
  SHARED_ACCOMMODATION,
  FAMILY_ACCOMMODATION,
  ADDITIONAL_FAMILY_ACCOMMODATION,
  PREFERRED_SUBJECT,
  SERVICE,
  ACCOMMODATION_STATUS,
  ASSIGNMENT_STATUS,
  SMS_CAMPAIGN_TYPE,
  SMS_CAMPAIGN_STATUS,
  SMS_LOG_STATUS,
  values,
};
